### ISSUE TITLE
Remember the Sabbath Day and Keep it Holy (4/30/23)

### ISSUE THREAD

**Issue by eigenscribe** [eigenscribe/projLevitate#10]
### Discussed in https://github.com/sofiascriber/serendipity/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **sofiascriber** April 30, 2023</sup>
Ideas
- Random walk  
  - ❓ How to choose transition probabilities?
  - 💡 Compare steady states of each initial state for a given transition matrix (should all be equal 🤔)
  - 💡 Compare steady states of different transition matrices for a given initial state
- Kuramoto model  
  - ❓ How to choose natural frequencies?
  - ❓ How to choose initial conditions?  
    - 1️⃣ Set $\theta_i(0)=0$ and $\dot{\theta}_i(0)=\omega_i$
    - 2️⃣ Set $\theta_i(0) \sim \text{Unif}\big([0,2\pi]\big)$ and $\dot{\theta}_i(0)=\omega_i$</div>

**Comment by sofiascriber** [comment]
2/18/23
![subversive network (250x250)](https://user-images.githubusercontent.com/111261353/219901195-4076868e-7e46-4930-ab98-48b0a28e06ee.png)  
--- 

🔗[Helpful Link](https://towardsdatascience.com/brief-introduction-to-markov-chains-2c8cab9c98ab)

Adjacency Matrix:
```matlab
  A = [
          0 1 1 0 0 1 0 0 0 0;    % 1
          1 0 1 0 1 1 0 0 0 0;    % 2
          1 1 0 1 0 1 0 0 0 0;    % 3
          0 0 1 0 1 1 1 0 0 0;    % 4
          0 1 0 1 0 1 0 1 0 0;    % 5
          1 1 1 1 1 0 1 1 1 0;    % 6
          0 0 0 1 0 1 0 1 1 1;    % 7
          0 0 0 0 1 1 1 0 1 1;    % 8
          0 0 0 0 0 1 1 1 0 1;    % 9
          0 0 0 0 0 0 1 1 1 0;    % 10
      ] ;
```

Transition Matrix:
```matlab
  P = [
           0  1/3 1/3  0   0  1/3  0   0   0   0;    % 1
          1/4  0  1/4  0  1/4 1/4  0   0   0   0;    % 2
          1/4 1/4  0  1/4  0  1/4  0   0   0   0;    % 3
           0   0  1/4  0  1/4 1/4 1/4  0   0   0;    % 4
           0  1/4  0  1/4  0  1/4  0  1/4  0   0;    % 5
          1/8 1/8 1/8 1/8 1/8  0  1/8 1/8 1/8  0;    % 6
           0   0   0  1/5  0  1/5  0  1/5 1/5 1/5;    % 7
           0   0   0   0  1/5 1/5 1/5  0  1/5 1/5;    % 8
           0   0   0   0   0  1/4 1/4 1/4  0  1/4;    % 9
           0   0   0   0   0   0  1/3 1/3 1/3  0;    % 10
      ];
```
## 2/20/23
🔗[Probability Models](https://www.math.wustl.edu/~feres/Math450Lect01.pdf)
